---
version: '3.0'
services:
  logstash:
    image: docker.elastic.co/logstash/logstash:6.0.1    
    volumes:
      - ./logstash/pipeline/:/usr/share/logstash/pipeline/
    networks:
      - elastic-stack    

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.0.1
    networks:
      - elastic-stack

  kibana:
    image: docker.elastic.co/kibana/kibana:6.0.1    
    ports: [ '5601:5601' ]
    networks:
      - elastic-stack   

  filebeat: 
    image: docker.elastic.co/beats/filebeat:6.0.1    
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./filebeat/log:/mnt/log/
      - ./filebeat/prospectors.d/:/usr/share/filebeat/prospectors.d/
    networks:
      - elastic-stack
    
networks:
  elastic-stack: